version: '3.4'

services:
    localeyesappsqlserver:
      container_name: localeyesappsqlserver
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: tdi87269xsu+!
        MYSQL_DATABASE: LocalEyesAppServiceDb
        MYSQL_USER: localeyesapp
        MYSQL_PASSWORD: tdi87269xsu+!
      volumes:
        - /var/lib/init_db/localeyes.sql:/docker-entrypoint-initdb.d/localeyes.sql

    localeyesappwebapi:
      image: fixitmedia/localeyeswebapi:latest
      restart: always
      ports:
        - 5000:5000
      environment:
        - TZ=Europe/Copenhage
        - MYSQL_HOST=localeyesappsqlserver
        - MYSQL_PORT=3306
        - MYSQL_USER=localeyesapp
        - MYSQL_PASSWORD=tdi87269xsu+!
        - MYSQL_NAME=LocalEyesAppServiceDb

      links:
        - localeyesappsqlserver